id: IFE4F484A
legacy_id: P010514
ocr_import_info:
  bdrc_scan_id: W22277
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T20:03:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:14:06.272892+00:00'
last_modified: 2022-09-02 05:21:04.644680
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22277
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22277
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཏཱ་ར་ནཱ་ཐ། ༼རྟག་བརྟན་ཕུན་ཚོགས་གླིང་གི་པར་མ།༽
  author: ཇོ་ནང་རྗེ་བཙུན་ཏཱ་ར་ནཱ་ཐ།
statistics:
  ocr_word_mean_confidence_index: 0.6250527753033348
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I2324:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2324
      total_pages: 832
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2324.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6830414290706756
    legacy_id: v012
  I2319:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2319
      total_pages: 964
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2319.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6036655830605021
    legacy_id: v007
  I2314:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2314
      total_pages: 960
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2314.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6280937598911925
    legacy_id: v002
  I2323:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2323
      total_pages: 966
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2323.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6158083541462118
    legacy_id: v011
  I2329:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2329
      total_pages: 622
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I2329.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7161692097934904
    legacy_id: v017
  I2315:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2315
      total_pages: 958
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2315.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6378540808554971
    legacy_id: v003
  I2317:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2317
      total_pages: 948
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2317.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6212801417965652
    legacy_id: v005
  I2316:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2316
      total_pages: 878
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2316.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6186371465637244
    legacy_id: v004
  I2312:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2312
      total_pages: 940
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2312.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6104270174969318
    legacy_id: v001
  I2318:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2318
      total_pages: 972
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2318.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6202591799815581
    legacy_id: v006
  I2327:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2327
      total_pages: 1036
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I2327.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6244822738913265
    legacy_id: v015
  I2322:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2322
      total_pages: 964
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2322.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.624287218332462
    legacy_id: v010
  I2320:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2320
      total_pages: 1022
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2320.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6487497607806394
    legacy_id: v008
  I2321:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2321
      total_pages: 1030
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2321.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5980089513859963
    legacy_id: v009
  I2325:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2325
      total_pages: 766
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I2325.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6391854936493077
    legacy_id: v013
  I2328:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2328
      total_pages: 1038
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I2328.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6833183242427128
    legacy_id: v016
  I2326:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2326
      total_pages: 808
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I2326.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5372650375180983
    legacy_id: v014
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
