id: IFE4F484A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:11:54+00:00'
last_modified: '2022-06-08T14:09:35.469491+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22277
  title: གསུང་འབུམ། ཏཱ་ར་ནཱ་ཐ། ༼རྟག་བརྟན་ཕུན་ཚོགས་གླིང་གི་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4487':
      image_group_id: I2312
      title: ''
      total_pages: 940
      order: 1
      base_file: 4487.txt
    '1453':
      image_group_id: I2314
      title: ''
      total_pages: 960
      order: 2
      base_file: 1453.txt
    250F:
      image_group_id: I2315
      title: ''
      total_pages: 958
      order: 3
      base_file: 250F.txt
    0CD0:
      image_group_id: I2316
      title: ''
      total_pages: 878
      order: 4
      base_file: 0CD0.txt
    08B0:
      image_group_id: I2317
      title: ''
      total_pages: 948
      order: 5
      base_file: 08B0.txt
    '4618':
      image_group_id: I2318
      title: ''
      total_pages: 972
      order: 6
      base_file: 4618.txt
    '4645':
      image_group_id: I2319
      title: ''
      total_pages: 964
      order: 7
      base_file: 4645.txt
    FF41:
      image_group_id: I2320
      title: ''
      total_pages: 1022
      order: 8
      base_file: FF41.txt
    D9AA:
      image_group_id: I2321
      title: ''
      total_pages: 1030
      order: 9
      base_file: D9AA.txt
    94AC:
      image_group_id: I2322
      title: ''
      total_pages: 964
      order: 10
      base_file: 94AC.txt
    7D38:
      image_group_id: I2323
      title: ''
      total_pages: 966
      order: 11
      base_file: 7D38.txt
    B0B4:
      image_group_id: I2324
      title: ''
      total_pages: 832
      order: 12
      base_file: B0B4.txt
    B02A:
      image_group_id: I2325
      title: ''
      total_pages: 766
      order: 13
      base_file: B02A.txt
    3B4C:
      image_group_id: I2326
      title: ''
      total_pages: 808
      order: 14
      base_file: 3B4C.txt
    11FF:
      image_group_id: I2327
      title: ''
      total_pages: 1036
      order: 15
      base_file: 11FF.txt
    A2BA:
      image_group_id: I2328
      title: ''
      total_pages: 1038
      order: 16
      base_file: A2BA.txt
    '5451':
      image_group_id: I2329
      title: ''
      total_pages: 622
      order: 17
      base_file: 5451.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
